name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      SHA:
        description: 'Commit SHA from DBM Unified'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SHA: ${{ github.event.inputs.SHA }}

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
